appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: QmYrGBbVccDVkBigeeBwsM7OEwtotMYk8IFp/5e8Y23Nt5WsrskckXhlnXc9IcRdItBJUz7qOdNyHo9z4vNNeHkswosoZLn8CfP0g1TARB4fIF/gNrny41rai9JcE3wTlaX7n+WjHQz3cQjHhQnAT8e1kLacK4q9nIGEHH783zlWU7+02KvaHmlHTGUopSQCNXb5vsHtLkuiPahygVfVFWUNizJ95e+Nku5jGeeYKmOqMIe9vqkpvn7fSfSyFAkIginyXMOkyx4yuL9j1ZfWnnlukQke3wb/sjpvckbRM3dhuk+7VkmGv/mH5gpnLGvsWjvwSVh9yDBfl1Dfw6+eR4wy5DFJWuJNotu2SrRV1M2X88PremD9vSaVkHSvW4wykmGO4wxqKnTnbtx5rirP0Xc/0WMs2iUXNgqYiev5+q/6aH0SqEtNRr+yuAG2s7yRNVVebvQIcRo7A2poRrjwkRzXZefXIG1RpJks4LEEKDlyqljFuxRWOqWJAlrwCYIBOkTjBaqgkiZZiLkDAaKnqxwiYpw3dUk3rUsACLARU4rCL0hMkq418niyk7bOYlVKgKBSZkZMt3hTV8o5Iy5TJ8/PECaqI3Jybwc9eYkU0LHvL8ns7fZkLYAGZuH1zYNotirjY0BBicR7R3PhzCJIqmlS/7ZbIIoYbgwMWrNg4GA=
